# render.yaml
# Infrastructure-as-Code configuration for the Family Hub platform on Render.
# This file defines the backend web service and the MongoDB database.
# It is safe to commit this file to version control.

services:
  # Backend Web Service (Node.js with Express)
  - type: web
    name: family-hub-backend
    env: node
    plan: starter # You can change this to a paid plan for more resources
    repo: https://github.com/YOUR_USERNAME/backend # IMPORTANT: Replace with your backend repo URL
    branch: main
    
    # Build and start commands for a standard Node.js app
    buildCommand: "npm install"
    startCommand: "node src/app.js"
    
    # Health check for zero-downtime deploys. Render will ping this endpoint.
    healthCheckPath: /api/health
    
    # Environment variables section
    # Secrets should be set in the Render dashboard Environment tab.
    # Values set in the dashboard will override any placeholders here.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: family-hub-db      # This must match the name of the database service below
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT # Render provides the port, but setting it here is good practice
        value: 10000 
      - key: JWT_SECRET
        generateValue: true # Instructs Render to generate and manage this secret for you
      - key: GOOGLE_CLIENT_ID
        value: YOUR_GOOGLE_CLIENT_ID # Placeholder: Set the real value in the Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        value: YOUR_GOOGLE_CLIENT_SECRET # Placeholder: Set the real value in the Render dashboard
      - key: CLIENT_URL
        value: https://your-netlify-app-name.netlify.app # IMPORTANT: Replace with your frontend's deployed URL

  # MongoDB Database Service
  - type: pserv # Private Service, not exposed to the public internet
    name: family-hub-db
    env: mongodb
    plan: starter # You can change this to a paid plan for more resources
    # Optionally specify a MongoDB version if needed
    # mongoVersion: "6.0" 
